alias reloadsh="source ~/.zshrc && echo Shell Config Reloaded!!!"
alias zshconfig="code ~/.zshrc"
alias clr="clear;ls;pwd"
alias ls="gls --color=auto --group-directories-first -ltrh"
alias flushdns="dscacheutil -flushcache && sudo killall -HUP mDNSResponde"
alias ll="$(brew --prefix coreutils)/libexec/gnubin/ls -ahlF --color --group-directories-first"
alias k="kubectl"
alias kx="kubectx"
alias weather="curl -4 http://wttr.in"